name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2

  - name: Install dbdocs
    run: sudo npm install -g dbdocs

  - name: Check dbdocs
    run: dbdocs

  - name: Update dbdocs project
    env:
      DBDOCS_TOKEN: eyJhbGciOi...
    run: dbdocs build ./ecommerce.dbml
